### ISSUE TITLE
Assignment operator does not work for gsMeshes with edges.

### ISSUE THREAD

**Issue by osmihran** [gismo/gismo#448]
Consider the following example, which tries to create a small mesh and make a copy of it.
```cpp
/** File to demonstrate the problem with gsMesh& operator=.
 * The mesh looks as follows.
 * +---+
 * |\  |
 * | \ |
 * |  \|
 * +---+
 */

#include <gismo.h>
#include "gsUtils/gsMesh/gsMesh.h"

using namespace gismo;

int main()
{
    gsMesh<real_t> orig;
    orig.reserve(4, 2, 5);

    typename gsMesh<real_t>::VertexHandle v[4];
    v[0] = orig.addVertex(0, 0);
    v[1] = orig.addVertex(1, 0);
    v[2] = orig.addVertex(1, 1);
    v[3] = orig.addVertex(0, 1);

    orig.addFace(v[0], v[1], v[3]);
    orig.addFace(v[3], v[1], v[3]);

    orig.addEdge(v[0], v[1]);
    orig.addEdge(v[1], v[2]);
    orig.addEdge(v[2], v[3]);
    orig.addEdge(v[3], v[0]);
    orig.addEdge(v[0], v[2]);

    gsMesh<real_t> copy = orig;
    gsInfo << copy << std::endl;

    return 0;
}
```
This fails. Here's the gdb output:
```
/usr/include/c++/9/debug/vector:427:
In function:
    std::__debug::vector<_Tp, _Allocator>::reference 
    std::__debug::vector<_Tp, 
    _Allocator>::operator[](std::__debug::vector<_Tp, 
    _Allocator>::size_type) [with _Tp = gismo::gsVertex<double>*; _Allocator 
    = std::allocator<gismo::gsVertex<double>*>; std::__debug::vector<_Tp, 
    _Allocator>::reference = gismo::gsVertex<double>*&; 
    std::__debug::vector<_Tp, _Allocator>::size_type = long unsigned int]

Error: attempt to subscript container with out-of-bounds index 4, but 
container only holds 4 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7fffffffddd0 {
      type = std::__debug::vector<gismo::gsVertex<double>*, std::allocator<gismo::gsVertex<double>*> >;
    }

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6620859 in __GI_abort () at abort.c:79
#2  0x00007ffff68a9149 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x000055555555d3f8 in std::__debug::vector<gismo::gsVertex<double>*, std::allocator<gismo::gsVertex<double>*> >::operator[] (this=0x7fffffffddd0, __n=4)
    at /usr/include/c++/9/debug/vector:427
#4  0x000055555555c3c8 in gismo::gsMesh<double>::operator= (this=0x7fffffffddc0, other=...) at /home/dominik/PRG/periodic-gismo/gismo/src/gsUtils/gsMesh/gsMesh.h:77
#5  0x000055555555b85f in gismo::gsMesh<double>::gsMesh (this=0x7fffffffddc0, mesh=...) at /home/dominik/PRG/periodic-gismo/gismo/src/gsUtils/gsMesh/gsMesh.h:52
#6  0x000055555555a9d9 in main () at /home/dominik/PRG/periodic-gismo/gismo/examples/issue-448.cpp:28
```
I think that both ```GISMO_ASSERT```s (lines 77 and 80 of gsMesh.h) are wrong, because they try to index both ```m_vertex``` and ```other.m_edge``` with ```i```:
```cpp
for (size_t i = 0; i != other.m_edge.size(); ++i)
{
    GISMO_ASSERT(other.m_edge[i].source->getId() == m_vertex[i]->getId(), "gsMesh(const gsMesh<T> & mesh): getId() of vertex and edge.source don't match");
    m_edge[i].source = m_vertex[other.m_edge[i].source->getId()];

    GISMO_ASSERT(other.m_edge[i].source->getId() == m_vertex[i]->getId(), "gsMesh(const gsMesh<T> & mesh): getId() of vertex and edge.target don't match");
    m_edge[i].target = m_vertex[other.m_edge[i].target->getId()];
}
```
My tendency would be to remove the two ```GISMO_ASSERTS``` altogether, because I am not entirely sure, how to fix them (maybe someone else has an idea?). Then it works fine:
```
> ./bin/issue-448 
gsMesh with 4 vertices, 5 edges and 2 faces.
```

I can append the fix to #421, where I am already touching this file, IIRC.

**Comment by filiatra** [comment]
Hi Dominik, indeed these asserts look wrong, please remove them and append to #421 as suggested..

**Comment by osmihran** [comment]
I will move the change into #421 as suggested.
