### ISSUE TITLE
Unable to download the Pygismo library via pip in Windows

### ISSUE THREAD

**Issue by Albe21072000** [gismo/gismo#738]
**Describe the bug**
When I try to install the pygismo library in Windows, using `pip install pygismo`, it fails to build the installable wheels and instead it displays the following error message:
`
Collecting pygismo
  Using cached pygismo-24.8.0.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from pygismo)
  Using cached numpy-2.1.1-cp311-cp311-win_amd64.whl.metadata (59 kB)
Using cached numpy-2.1.1-cp311-cp311-win_amd64.whl (12.9 MB)
Building wheels for collected packages: pygismo
  Building wheel for pygismo (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pygismo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [161 lines of output]
      C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\dist.py:294: InformationOnly: Normalizing '24.08.0' to '24.8.0'
        self.metadata.version = self._normalize_version(self.metadata.version)
      running bdist_wheel
      running build
      running build_ext
      -- Building for: Visual Studio 17 2022
      CMake Deprecation Warning at CMakeLists.txt:9 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
      -- The C compiler identification is MSVC 19.41.34120.0
      -- The CXX compiler identification is MSVC 19.41.34120.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - broken
      CMake Error at C:/Users/albeb/AppData/Local/Temp/pip-build-env-j6t6a3bo/overlay/Lib/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: 'C:/Users/albeb/AppData/Local/Temp/pip-install-021a5wkx/pygismo_21f8a87d501a4d02b031b69935d8091f/build/temp.win-amd64-cpython-311/Release/pygismo/CMakeFiles/CMakeScratch/TryCompile-4gh5a8'

          Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_becc5.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
          Versione di MSBuild 17.11.2+c078802d4 per .NET Framework
          Compilazione avviata 15/09/2024 19:11:29.

          Progetto "C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj" sul nodo 1 (destinazioni predefinite).
          PrepareForBuild:
            Creazione directory "cmTC_becc5.dir\Debug\".
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: la directory intermedia o la directory di output non puâ”œâ–“ risiedere nella directory temporanea perchâ”œÂ® tale condizione potrebbe causare problemi con la compilazione incrementale. [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
            L'output strutturato â”œÂ¿ abilitato. La formattazione della diagnostica del compilatore rifletterâ”œÃ¡ la gerarchia degli errori. Per altri dettagli, vedere https://aka.ms/cpp/structured-output.
            Creazione directory "C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\Debug\".
            Creazione directory "cmTC_becc5.dir\Debug\cmTC_becc5.tlog\".
          InitializeBuildStatus:
            Creazione di "cmTC_becc5.dir\Debug\cmTC_becc5.tlog\unsuccessfulbuild". â”œÃª stato specificato "AlwaysCreate".
            Aggiornamento timestamp di "cmTC_becc5.dir\Debug\cmTC_becc5.tlog\unsuccessfulbuild".
          ClCompile:
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_becc5.dir\Debug\\" /Fd"cmTC_becc5.dir\Debug\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\testCCompiler.c"
            Microsoft (R) C/C++ Optimizing Compiler versione 19.41.34120 per x64
            Copyright (C) Microsoft Corporation. Tutti i diritti  sono riservati.
            cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_becc5.dir\Debug\\" /Fd"cmTC_becc5.dir\Debug\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\testCCompiler.c"
            testCCompiler.c
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003: non â”œÂ¿ stato possibile eseguire il file eseguibile "CL.exe" dell'attivitâ”œÃ¡. System.IO.DirectoryNotFoundException: Impossibile trovare una parte del percorso 'C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.dir\Debug\cmTC_becc5.tlog'. [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.CPPTasks.CL.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          Compilazione progetto "C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj" (destinazioni predefinite) NON COMPLETATA.

          Compilazione NON RIUSCITA.

          "C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj" (destinazione predefinita) (1) ->
          (destinazione: PrepareForBuild) ->
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: la directory intermedia o la directory di output non puâ”œâ–“ risiedere nella directory temporanea perchâ”œÂ® tale condizione potrebbe causare problemi con la compilazione incrementale. [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]

          "C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj" (destinazione predefinita) (1) ->
          (destinazione: ClCompile) ->
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003: non â”œÂ¿ stato possibile eseguire il file eseguibile "CL.exe" dell'attivitâ”œÃ¡. System.IO.DirectoryNotFoundException: Impossibile trovare una parte del percorso 'C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.dir\Debug\cmTC_becc5.tlog'. [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.CPPTasks.CL.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(755,5): error MSB6003:    in Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\temp.win-amd64-cpython-311\Release\pygismo\CMakeFiles\CMakeScratch\TryCompile-4gh5a8\cmTC_becc5.vcxproj]

              Avvisi: 1
              Errori: 1

          Tempo trascorso 00:00:00.24

        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:80 (project)

      -- Configuring incomplete, errors occurred!
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\albeb\AppData\Local\Temp\pip-install-021a5wkx\pygismo_21f8a87d501a4d02b031b69935d8091f\build\lib.win-amd64-cpython-311\
      Traceback (most recent call last):
        File "C:\Users\albeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\albeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\albeb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\build_meta.py", line 421, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 230, in <module>
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
          dist.run_commands()
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\command\bdist_wheel.py", line 384, in run
          self.run_command("build")
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 98, in run
          _build_ext.run(self)
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\albeb\AppData\Local\Temp\pip-build-env-j6t6a3bo\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 218, in build_extension
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\albeb\\AppData\\Local\\Temp\\pip-install-021a5wkx\\pygismo_21f8a87d501a4d02b031b69935d8091f', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\albeb\\AppData\\Local\\Temp\\pip-install-021a5wkx\\pygismo_21f8a87d501a4d02b031b69935d8091f\\build\\lib.win-amd64-cpython-311\\', '-DPYTHON_EXECUTABLE=C:\\Users\\albeb\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\python.exe', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_BUILD_TYPE=Release', '-DGISMO_WITH_PYBIND11=ON', '-DGISMO_BUILD_EXAMPLES=OFF', '-DNOSNIPPETS=ON', '-Dpybind11_DIR=C:\\Users\\albeb\\AppData\\Local\\Temp\\pip-build-env-j6t6a3bo\\overlay\\Lib\\site-packages\\pybind11\\share\\cmake\\pybind11', '-A', 'x64', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\albeb\\AppData\\Local\\Temp\\pip-install-021a5wkx\\pygismo_21f8a87d501a4d02b031b69935d8091f\\build\\lib.win-amd64-cpython-311']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pygismo
Failed to build pygismo
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pygismo)
`

**To Reproduce**
Enter `pip install pygismo` in the Windows command prompt/PowerShell

**Expected behavior**
It should download and install the pygismo library.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 10.0.22631 build 22631
 - Branch/fork used: Pygismo 24.8.0

**Comment by ZZ-SEC** [comment]
I have met the same problem, and I solved this by adding 'f"-DCMAKE_CXX_STANDARD=20",'  in 'setup.py' lines 108-118 'cmake_args'.
Also, error C2766 may occur in file '/exernal/tclap/StandardTraits.h' line 142, delete lines 138-146 can fix this.

**Comment by hverhelst** [comment]
@Albe21072000 what is the current status of this issue?

**Comment by Albe21072000** [comment]
It is still failing to install pygismo via pip, the error is unchanged
